package com.zhangben.backend.mapper;

import com.zhangben.backend.model.FavoredUser;
import com.zhangben.backend.model.FavoredUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavoredUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    long countByExample(FavoredUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int deleteByExample(FavoredUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int insert(FavoredUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int insertSelective(FavoredUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    List<FavoredUser> selectByExample(FavoredUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    FavoredUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int updateByExampleSelective(@Param("row") FavoredUser row, @Param("example") FavoredUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int updateByExample(@Param("row") FavoredUser row, @Param("example") FavoredUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int updateByPrimaryKeySelective(FavoredUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favored_user
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int updateByPrimaryKey(FavoredUser row);
}