package com.zhangben.backend.mapper;

import com.zhangben.backend.model.Outcome;
import com.zhangben.backend.model.OutcomeExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface OutcomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    long countByExample(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int deleteByExample(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int insert(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int insertSelective(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    List<Outcome> selectByExampleWithBLOBs(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    List<Outcome> selectByExample(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    Outcome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByExampleSelective(@Param("row") Outcome row, @Param("example") OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") Outcome row, @Param("example") OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByExample(@Param("row") Outcome row, @Param("example") OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByPrimaryKeySelective(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByPrimaryKeyWithBLOBs(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByPrimaryKey(Outcome row);

    /**
     * 根据活动ID查询账单列表（本地化）
     * @param activityId 活动ID
     * @param language 语言代码 (zh-CN, en-US, ja-JP)
     */
    List<Map<String, Object>> selectByActivityId(@Param("activityId") Integer activityId, @Param("language") String language);

    /**
     * 软删除账单
     */
    int softDeleteById(@Param("id") Integer id);

    /**
     * V40: Get outcomes by activity ID (GDPR)
     */
    List<Outcome> selectOutcomesByActivityId(@Param("activityId") Integer activityId);

    /**
     * V40: Delete outcomes by activity ID (GDPR)
     */
    int deleteByActivityId(@Param("activityId") Integer activityId);

    /**
     * V40: Get outcomes by payer user ID (GDPR)
     */
    List<Outcome> selectByPayerUserId(@Param("payerUserId") Integer payerUserId);

    /**
     * V40: Delete outcomes by payer user ID (GDPR)
     */
    int deleteByPayerUserId(@Param("payerUserId") Integer payerUserId);

    /**
     * Seek-based 分页查询用户的所有记录（支出 + 收入）
     * @param userId 用户ID
     * @param lastId 上一页最后一条记录的ID（首页传 null）
     * @param monthStart 月份开始时间（可选）
     * @param monthEnd 月份结束时间（可选）
     * @param limit 每页数量
     */
    List<Outcome> selectPagedByUser(@Param("userId") Integer userId,
                                     @Param("lastId") Integer lastId,
                                     @Param("monthStart") java.time.LocalDateTime monthStart,
                                     @Param("monthEnd") java.time.LocalDateTime monthEnd,
                                     @Param("limit") Integer limit);

    /**
     * 统计某月总支出金额（仅 repay_flag=1 的支付记录）
     */
    Long sumMonthlyExpense(@Param("userId") Integer userId,
                           @Param("monthStart") java.time.LocalDateTime monthStart,
                           @Param("monthEnd") java.time.LocalDateTime monthEnd);

    /**
     * 获取用户有记录的月份列表（倒序）
     */
    List<String> selectDistinctMonths(@Param("userId") Integer userId);

    /**
     * 获取用户某月有记录的日期列表
     */
    List<Integer> selectDistinctDays(@Param("userId") Integer userId,
                                      @Param("monthStart") java.time.LocalDateTime monthStart,
                                      @Param("monthEnd") java.time.LocalDateTime monthEnd);
}