package com.zhangben.backend.mapper;

import com.zhangben.backend.model.Outcome;
import com.zhangben.backend.model.OutcomeExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface OutcomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    long countByExample(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int deleteByExample(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int insert(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int insertSelective(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    List<Outcome> selectByExampleWithBLOBs(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    List<Outcome> selectByExample(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    Outcome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByExampleSelective(@Param("row") Outcome row, @Param("example") OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") Outcome row, @Param("example") OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByExample(@Param("row") Outcome row, @Param("example") OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByPrimaryKeySelective(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByPrimaryKeyWithBLOBs(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    int updateByPrimaryKey(Outcome row);

    /**
     * 根据活动ID查询账单列表（本地化）
     * @param activityId 活动ID
     * @param language 语言代码 (zh-CN, en-US, ja-JP)
     */
    List<Map<String, Object>> selectByActivityId(@Param("activityId") Integer activityId, @Param("language") String language);

    /**
     * 软删除账单
     */
    int softDeleteById(@Param("id") Integer id);

    /**
     * V40: Get outcomes by activity ID (GDPR)
     */
    List<Outcome> selectOutcomesByActivityId(@Param("activityId") Integer activityId);

    /**
     * V40: Delete outcomes by activity ID (GDPR)
     */
    int deleteByActivityId(@Param("activityId") Integer activityId);

    /**
     * V40: Get outcomes by payer user ID (GDPR)
     */
    List<Outcome> selectByPayerUserId(@Param("payerUserId") Integer payerUserId);

    /**
     * V40: Delete outcomes by payer user ID (GDPR)
     */
    int deleteByPayerUserId(@Param("payerUserId") Integer payerUserId);
}