package com.zhangben.backend.mapper;

import com.zhangben.backend.model.Outcome;
import com.zhangben.backend.model.OutcomeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutcomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    long countByExample(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int deleteByExample(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int insert(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int insertSelective(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    List<Outcome> selectByExampleWithBLOBs(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    List<Outcome> selectByExample(OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    Outcome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int updateByExampleSelective(@Param("row") Outcome row, @Param("example") OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") Outcome row, @Param("example") OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int updateByExample(@Param("row") Outcome row, @Param("example") OutcomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int updateByPrimaryKeySelective(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int updateByPrimaryKeyWithBLOBs(Outcome row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Sat Jan 24 17:19:35 JST 2026
     */
    int updateByPrimaryKey(Outcome row);
}