package com.zhangben.backend.mapper;

import com.zhangben.backend.model.OutcomeParticipant;
import com.zhangben.backend.model.OutcomeParticipantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutcomeParticipantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    long countByExample(OutcomeParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    int deleteByExample(OutcomeParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    int insert(OutcomeParticipant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    int insertSelective(OutcomeParticipant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    List<OutcomeParticipant> selectByExample(OutcomeParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    OutcomeParticipant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    int updateByExampleSelective(@Param("row") OutcomeParticipant row, @Param("example") OutcomeParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    int updateByExample(@Param("row") OutcomeParticipant row, @Param("example") OutcomeParticipantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    int updateByPrimaryKeySelective(OutcomeParticipant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome_participant
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    int updateByPrimaryKey(OutcomeParticipant row);

    /**
     * 查询待确认的还款记录（当前用户作为债权人）
     */
    List<OutcomeParticipant> selectPendingConfirmations(@Param("creditorId") Integer creditorId);

    /**
     * 根据还款ID和债权人ID查询参与记录
     */
    OutcomeParticipant selectByOutcomeAndUser(@Param("outcomeId") Integer outcomeId, @Param("userId") Integer userId);
}