package com.zhangben.backend.mapper;

import com.zhangben.backend.model.PayStyle;
import com.zhangben.backend.model.PayStyleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    long countByExample(PayStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int deleteByExample(PayStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int insert(PayStyle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int insertSelective(PayStyle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    List<PayStyle> selectByExample(PayStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    PayStyle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int updateByExampleSelective(@Param("row") PayStyle row, @Param("example") PayStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int updateByExample(@Param("row") PayStyle row, @Param("example") PayStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int updateByPrimaryKeySelective(PayStyle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_style
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    int updateByPrimaryKey(PayStyle row);
}