package com.zhangben.backend.mapper;

import com.zhangben.backend.model.User;
import com.zhangben.backend.model.UserExample;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    int updateByPrimaryKey(User row);

    /**
     * V40: GDPR - Anonymize user data (soft delete)
     * Clears all PII while keeping the record for referential integrity
     */
    int anonymizeUser(@Param("userId") Integer userId);

    /**
     * V42: 查找即将到期的订阅（排除永久会员和已发送提醒的用户）
     */
    List<User> selectExpiringSubscriptions(
        @Param("now") LocalDateTime now,
        @Param("expiryThreshold") LocalDateTime expiryThreshold
    );

    /**
     * V42: 重置所有用户的提醒发送状态
     */
    int resetSubscriptionReminderStatus();

    /**
     * V43: 按 Microsoft ID 查找用户
     */
    User selectByMicrosoftId(@Param("microsoftId") String microsoftId);
}