package com.zhangben.backend.model;

import java.util.Date;

public class FavoredUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favored_user.ID
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favored_user.user_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favored_user.favored_user_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Integer favoredUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favored_user.created_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favored_user.updated_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favored_user.ID
     *
     * @return the value of favored_user.ID
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favored_user.ID
     *
     * @param id the value for favored_user.ID
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favored_user.user_id
     *
     * @return the value of favored_user.user_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favored_user.user_id
     *
     * @param userId the value for favored_user.user_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favored_user.favored_user_id
     *
     * @return the value of favored_user.favored_user_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Integer getFavoredUserId() {
        return favoredUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favored_user.favored_user_id
     *
     * @param favoredUserId the value for favored_user.favored_user_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setFavoredUserId(Integer favoredUserId) {
        this.favoredUserId = favoredUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favored_user.created_at
     *
     * @return the value of favored_user.created_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favored_user.created_at
     *
     * @param createdAt the value for favored_user.created_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favored_user.updated_at
     *
     * @return the value of favored_user.updated_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favored_user.updated_at
     *
     * @param updatedAt the value for favored_user.updated_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}