package com.zhangben.backend.model;

public class OutcomeParticipant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome_participant.id
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome_participant.outcome_id
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    private Integer outcomeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome_participant.user_id
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    private Integer userId;

    /**
     * 份额数量，默认1份
     */
    private Integer shares;

    /**
     * 确认状态: 0=待确认, 1=已确认
     */
    private Byte confirmStatus;

    /**
     * 确认时间
     */
    private java.time.LocalDateTime confirmedAt;

    /**
     * 确认人ID
     */
    private Integer confirmedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome_participant.id
     *
     * @return the value of outcome_participant.id
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome_participant.id
     *
     * @param id the value for outcome_participant.id
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome_participant.outcome_id
     *
     * @return the value of outcome_participant.outcome_id
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    public Integer getOutcomeId() {
        return outcomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome_participant.outcome_id
     *
     * @param outcomeId the value for outcome_participant.outcome_id
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    public void setOutcomeId(Integer outcomeId) {
        this.outcomeId = outcomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome_participant.user_id
     *
     * @return the value of outcome_participant.user_id
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome_participant.user_id
     *
     * @param userId the value for outcome_participant.user_id
     *
     * @mbg.generated Fri Jan 23 12:54:27 JST 2026
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getShares() {
        return shares;
    }

    public void setShares(Integer shares) {
        this.shares = shares;
    }

    public Byte getConfirmStatus() {
        return confirmStatus;
    }

    public void setConfirmStatus(Byte confirmStatus) {
        this.confirmStatus = confirmStatus;
    }

    public java.time.LocalDateTime getConfirmedAt() {
        return confirmedAt;
    }

    public void setConfirmedAt(java.time.LocalDateTime confirmedAt) {
        this.confirmedAt = confirmedAt;
    }

    public Integer getConfirmedBy() {
        return confirmedBy;
    }

    public void setConfirmedBy(Integer confirmedBy) {
        this.confirmedBy = confirmedBy;
    }
}