package com.zhangben.backend.model;

import java.time.LocalDateTime;

public class Outcome {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.id
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.amount
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.payer_userid
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private Integer payerUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.target_userid
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private Integer targetUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.per_amount
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private Long perAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.extra_participants
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private Integer extraParticipants;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.repay_flag
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private Byte repayFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.pay_datetime
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private LocalDateTime payDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.style_id
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private Integer styleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.comment
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.deleted_flag
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private Byte deletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.created_at
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.updated_at
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outcome.locaton
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    private byte[] locaton;

    /**
     * 总份额数
     */
    private Integer totalShares;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.id
     *
     * @return the value of outcome.id
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.id
     *
     * @param id the value for outcome.id
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.amount
     *
     * @return the value of outcome.amount
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.amount
     *
     * @param amount the value for outcome.amount
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.payer_userid
     *
     * @return the value of outcome.payer_userid
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Integer getPayerUserid() {
        return payerUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.payer_userid
     *
     * @param payerUserid the value for outcome.payer_userid
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setPayerUserid(Integer payerUserid) {
        this.payerUserid = payerUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.target_userid
     *
     * @return the value of outcome.target_userid
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Integer getTargetUserid() {
        return targetUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.target_userid
     *
     * @param targetUserid the value for outcome.target_userid
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setTargetUserid(Integer targetUserid) {
        this.targetUserid = targetUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.per_amount
     *
     * @return the value of outcome.per_amount
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Long getPerAmount() {
        return perAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.per_amount
     *
     * @param perAmount the value for outcome.per_amount
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setPerAmount(Long perAmount) {
        this.perAmount = perAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.extra_participants
     *
     * @return the value of outcome.extra_participants
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Integer getExtraParticipants() {
        return extraParticipants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.extra_participants
     *
     * @param extraParticipants the value for outcome.extra_participants
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setExtraParticipants(Integer extraParticipants) {
        this.extraParticipants = extraParticipants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.repay_flag
     *
     * @return the value of outcome.repay_flag
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Byte getRepayFlag() {
        return repayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.repay_flag
     *
     * @param repayFlag the value for outcome.repay_flag
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setRepayFlag(Byte repayFlag) {
        this.repayFlag = repayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.pay_datetime
     *
     * @return the value of outcome.pay_datetime
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public LocalDateTime getPayDatetime() {
        return payDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.pay_datetime
     *
     * @param payDatetime the value for outcome.pay_datetime
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setPayDatetime(LocalDateTime payDatetime) {
        this.payDatetime = payDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.style_id
     *
     * @return the value of outcome.style_id
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Integer getStyleId() {
        return styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.style_id
     *
     * @param styleId the value for outcome.style_id
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setStyleId(Integer styleId) {
        this.styleId = styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.comment
     *
     * @return the value of outcome.comment
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.comment
     *
     * @param comment the value for outcome.comment
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.deleted_flag
     *
     * @return the value of outcome.deleted_flag
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Byte getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.deleted_flag
     *
     * @param deletedFlag the value for outcome.deleted_flag
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setDeletedFlag(Byte deletedFlag) {
        this.deletedFlag = deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.created_at
     *
     * @return the value of outcome.created_at
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.created_at
     *
     * @param createdAt the value for outcome.created_at
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.updated_at
     *
     * @return the value of outcome.updated_at
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.updated_at
     *
     * @param updatedAt the value for outcome.updated_at
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outcome.locaton
     *
     * @return the value of outcome.locaton
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public byte[] getLocaton() {
        return locaton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outcome.locaton
     *
     * @param locaton the value for outcome.locaton
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setLocaton(byte[] locaton) {
        this.locaton = locaton;
    }

    public Integer getTotalShares() {
        return totalShares;
    }

    public void setTotalShares(Integer totalShares) {
        this.totalShares = totalShares;
    }
}