package com.zhangben.backend.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class OutcomeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public OutcomeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Long value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Long value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Long value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Long value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Long value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Long> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Long> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Long value1, Long value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Long value1, Long value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andPayerUseridIsNull() {
            addCriterion("payer_userid is null");
            return (Criteria) this;
        }

        public Criteria andPayerUseridIsNotNull() {
            addCriterion("payer_userid is not null");
            return (Criteria) this;
        }

        public Criteria andPayerUseridEqualTo(Integer value) {
            addCriterion("payer_userid =", value, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andPayerUseridNotEqualTo(Integer value) {
            addCriterion("payer_userid <>", value, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andPayerUseridGreaterThan(Integer value) {
            addCriterion("payer_userid >", value, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andPayerUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("payer_userid >=", value, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andPayerUseridLessThan(Integer value) {
            addCriterion("payer_userid <", value, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andPayerUseridLessThanOrEqualTo(Integer value) {
            addCriterion("payer_userid <=", value, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andPayerUseridIn(List<Integer> values) {
            addCriterion("payer_userid in", values, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andPayerUseridNotIn(List<Integer> values) {
            addCriterion("payer_userid not in", values, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andPayerUseridBetween(Integer value1, Integer value2) {
            addCriterion("payer_userid between", value1, value2, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andPayerUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("payer_userid not between", value1, value2, "payerUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridIsNull() {
            addCriterion("target_userid is null");
            return (Criteria) this;
        }

        public Criteria andTargetUseridIsNotNull() {
            addCriterion("target_userid is not null");
            return (Criteria) this;
        }

        public Criteria andTargetUseridEqualTo(Integer value) {
            addCriterion("target_userid =", value, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridNotEqualTo(Integer value) {
            addCriterion("target_userid <>", value, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridGreaterThan(Integer value) {
            addCriterion("target_userid >", value, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("target_userid >=", value, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridLessThan(Integer value) {
            addCriterion("target_userid <", value, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridLessThanOrEqualTo(Integer value) {
            addCriterion("target_userid <=", value, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridIn(List<Integer> values) {
            addCriterion("target_userid in", values, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridNotIn(List<Integer> values) {
            addCriterion("target_userid not in", values, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridBetween(Integer value1, Integer value2) {
            addCriterion("target_userid between", value1, value2, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andTargetUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("target_userid not between", value1, value2, "targetUserid");
            return (Criteria) this;
        }

        public Criteria andPerAmountIsNull() {
            addCriterion("per_amount is null");
            return (Criteria) this;
        }

        public Criteria andPerAmountIsNotNull() {
            addCriterion("per_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPerAmountEqualTo(Long value) {
            addCriterion("per_amount =", value, "perAmount");
            return (Criteria) this;
        }

        public Criteria andPerAmountNotEqualTo(Long value) {
            addCriterion("per_amount <>", value, "perAmount");
            return (Criteria) this;
        }

        public Criteria andPerAmountGreaterThan(Long value) {
            addCriterion("per_amount >", value, "perAmount");
            return (Criteria) this;
        }

        public Criteria andPerAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("per_amount >=", value, "perAmount");
            return (Criteria) this;
        }

        public Criteria andPerAmountLessThan(Long value) {
            addCriterion("per_amount <", value, "perAmount");
            return (Criteria) this;
        }

        public Criteria andPerAmountLessThanOrEqualTo(Long value) {
            addCriterion("per_amount <=", value, "perAmount");
            return (Criteria) this;
        }

        public Criteria andPerAmountIn(List<Long> values) {
            addCriterion("per_amount in", values, "perAmount");
            return (Criteria) this;
        }

        public Criteria andPerAmountNotIn(List<Long> values) {
            addCriterion("per_amount not in", values, "perAmount");
            return (Criteria) this;
        }

        public Criteria andPerAmountBetween(Long value1, Long value2) {
            addCriterion("per_amount between", value1, value2, "perAmount");
            return (Criteria) this;
        }

        public Criteria andPerAmountNotBetween(Long value1, Long value2) {
            addCriterion("per_amount not between", value1, value2, "perAmount");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsIsNull() {
            addCriterion("extra_participants is null");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsIsNotNull() {
            addCriterion("extra_participants is not null");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsEqualTo(Integer value) {
            addCriterion("extra_participants =", value, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsNotEqualTo(Integer value) {
            addCriterion("extra_participants <>", value, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsGreaterThan(Integer value) {
            addCriterion("extra_participants >", value, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsGreaterThanOrEqualTo(Integer value) {
            addCriterion("extra_participants >=", value, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsLessThan(Integer value) {
            addCriterion("extra_participants <", value, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsLessThanOrEqualTo(Integer value) {
            addCriterion("extra_participants <=", value, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsIn(List<Integer> values) {
            addCriterion("extra_participants in", values, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsNotIn(List<Integer> values) {
            addCriterion("extra_participants not in", values, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsBetween(Integer value1, Integer value2) {
            addCriterion("extra_participants between", value1, value2, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andExtraParticipantsNotBetween(Integer value1, Integer value2) {
            addCriterion("extra_participants not between", value1, value2, "extraParticipants");
            return (Criteria) this;
        }

        public Criteria andRepayFlagIsNull() {
            addCriterion("repay_flag is null");
            return (Criteria) this;
        }

        public Criteria andRepayFlagIsNotNull() {
            addCriterion("repay_flag is not null");
            return (Criteria) this;
        }

        public Criteria andRepayFlagEqualTo(Byte value) {
            addCriterion("repay_flag =", value, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andRepayFlagNotEqualTo(Byte value) {
            addCriterion("repay_flag <>", value, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andRepayFlagGreaterThan(Byte value) {
            addCriterion("repay_flag >", value, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andRepayFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("repay_flag >=", value, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andRepayFlagLessThan(Byte value) {
            addCriterion("repay_flag <", value, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andRepayFlagLessThanOrEqualTo(Byte value) {
            addCriterion("repay_flag <=", value, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andRepayFlagIn(List<Byte> values) {
            addCriterion("repay_flag in", values, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andRepayFlagNotIn(List<Byte> values) {
            addCriterion("repay_flag not in", values, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andRepayFlagBetween(Byte value1, Byte value2) {
            addCriterion("repay_flag between", value1, value2, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andRepayFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("repay_flag not between", value1, value2, "repayFlag");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeIsNull() {
            addCriterion("pay_datetime is null");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeIsNotNull() {
            addCriterion("pay_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeEqualTo(LocalDateTime value) {
            addCriterion("pay_datetime =", value, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("pay_datetime <>", value, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("pay_datetime >", value, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("pay_datetime >=", value, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeLessThan(LocalDateTime value) {
            addCriterion("pay_datetime <", value, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("pay_datetime <=", value, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeIn(List<LocalDateTime> values) {
            addCriterion("pay_datetime in", values, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("pay_datetime not in", values, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("pay_datetime between", value1, value2, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andPayDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("pay_datetime not between", value1, value2, "payDatetime");
            return (Criteria) this;
        }

        public Criteria andStyleIdIsNull() {
            addCriterion("style_id is null");
            return (Criteria) this;
        }

        public Criteria andStyleIdIsNotNull() {
            addCriterion("style_id is not null");
            return (Criteria) this;
        }

        public Criteria andStyleIdEqualTo(Integer value) {
            addCriterion("style_id =", value, "styleId");
            return (Criteria) this;
        }

        public Criteria andStyleIdNotEqualTo(Integer value) {
            addCriterion("style_id <>", value, "styleId");
            return (Criteria) this;
        }

        public Criteria andStyleIdGreaterThan(Integer value) {
            addCriterion("style_id >", value, "styleId");
            return (Criteria) this;
        }

        public Criteria andStyleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("style_id >=", value, "styleId");
            return (Criteria) this;
        }

        public Criteria andStyleIdLessThan(Integer value) {
            addCriterion("style_id <", value, "styleId");
            return (Criteria) this;
        }

        public Criteria andStyleIdLessThanOrEqualTo(Integer value) {
            addCriterion("style_id <=", value, "styleId");
            return (Criteria) this;
        }

        public Criteria andStyleIdIn(List<Integer> values) {
            addCriterion("style_id in", values, "styleId");
            return (Criteria) this;
        }

        public Criteria andStyleIdNotIn(List<Integer> values) {
            addCriterion("style_id not in", values, "styleId");
            return (Criteria) this;
        }

        public Criteria andStyleIdBetween(Integer value1, Integer value2) {
            addCriterion("style_id between", value1, value2, "styleId");
            return (Criteria) this;
        }

        public Criteria andStyleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("style_id not between", value1, value2, "styleId");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNull() {
            addCriterion("deleted_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNotNull() {
            addCriterion("deleted_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagEqualTo(Byte value) {
            addCriterion("deleted_flag =", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotEqualTo(Byte value) {
            addCriterion("deleted_flag <>", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThan(Byte value) {
            addCriterion("deleted_flag >", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("deleted_flag >=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThan(Byte value) {
            addCriterion("deleted_flag <", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThanOrEqualTo(Byte value) {
            addCriterion("deleted_flag <=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIn(List<Byte> values) {
            addCriterion("deleted_flag in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotIn(List<Byte> values) {
            addCriterion("deleted_flag not in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagBetween(Byte value1, Byte value2) {
            addCriterion("deleted_flag between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("deleted_flag not between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(LocalDateTime value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(LocalDateTime value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(LocalDateTime value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<LocalDateTime> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outcome
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 28 08:42:00 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outcome
     *
     * @mbg.generated Wed Jan 28 08:42:00 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}