package com.zhangben.backend.model;

import java.util.Date;

public class PayStyle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.style_name
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private String styleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.parent_style_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Integer parentStyleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.created_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.updated_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_style.id
     *
     * @return the value of pay_style.id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.id
     *
     * @param id the value for pay_style.id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_style.style_name
     *
     * @return the value of pay_style.style_name
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public String getStyleName() {
        return styleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.style_name
     *
     * @param styleName the value for pay_style.style_name
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setStyleName(String styleName) {
        this.styleName = styleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_style.parent_style_id
     *
     * @return the value of pay_style.parent_style_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Integer getParentStyleId() {
        return parentStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.parent_style_id
     *
     * @param parentStyleId the value for pay_style.parent_style_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setParentStyleId(Integer parentStyleId) {
        this.parentStyleId = parentStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_style.created_at
     *
     * @return the value of pay_style.created_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.created_at
     *
     * @param createdAt the value for pay_style.created_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_style.updated_at
     *
     * @return the value of pay_style.updated_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.updated_at
     *
     * @param updatedAt the value for pay_style.updated_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}