package com.zhangben.backend.model;

import java.util.Date;

public class PayStyle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.style_name
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private String styleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.parent_style_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Integer parentStyleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.created_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_style.updated_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    private Date updatedAt;

    // V45: 分类系统扩展字段
    private String iconName;
    private String colorCode;
    private String groupName;      // daily, leisure, fixed
    private Boolean isFixed;
    private Float noiseLevel;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.id
     *
     * @param id the value for pay_style.id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_style.style_name
     *
     * @return the value of pay_style.style_name
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public String getStyleName() {
        return styleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.style_name
     *
     * @param styleName the value for pay_style.style_name
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setStyleName(String styleName) {
        this.styleName = styleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_style.parent_style_id
     *
     * @return the value of pay_style.parent_style_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Integer getParentStyleId() {
        return parentStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.parent_style_id
     *
     * @param parentStyleId the value for pay_style.parent_style_id
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setParentStyleId(Integer parentStyleId) {
        this.parentStyleId = parentStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_style.created_at
     *
     * @return the value of pay_style.created_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.created_at
     *
     * @param createdAt the value for pay_style.created_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_style.updated_at
     *
     * @return the value of pay_style.updated_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_style.updated_at
     *
     * @param updatedAt the value for pay_style.updated_at
     *
     * @mbg.generated Fri Jan 23 11:42:09 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getIconName() { return iconName; }
    public void setIconName(String iconName) { this.iconName = iconName; }

    public String getColorCode() { return colorCode; }
    public void setColorCode(String colorCode) { this.colorCode = colorCode; }

    public String getGroupName() { return groupName; }
    public void setGroupName(String groupName) { this.groupName = groupName; }

    public Boolean getIsFixed() { return isFixed; }
    public void setIsFixed(Boolean isFixed) { this.isFixed = isFixed; }

    public Float getNoiseLevel() { return noiseLevel; }
    public void setNoiseLevel(Float noiseLevel) { this.noiseLevel = noiseLevel; }
}