package com.zhangben.backend.model;

import java.time.LocalDateTime;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.google_id
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String googleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.secondname
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String secondname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.firstname
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.paypay_flag
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private Byte paypayFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.paypay_account
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String paypayAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bank_flag
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private Byte bankFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bank_name
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bank_branch
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String bankBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bank_account
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.profile_completed
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private Boolean profileCompleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_at
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updated_at
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.google_id
     *
     * @return the value of user.google_id
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getGoogleId() {
        return googleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.google_id
     *
     * @param googleId the value for user.google_id
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setGoogleId(String googleId) {
        this.googleId = googleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.secondname
     *
     * @return the value of user.secondname
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getSecondname() {
        return secondname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.secondname
     *
     * @param secondname the value for user.secondname
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setSecondname(String secondname) {
        this.secondname = secondname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.firstname
     *
     * @return the value of user.firstname
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.firstname
     *
     * @param firstname the value for user.firstname
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.paypay_flag
     *
     * @return the value of user.paypay_flag
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public Byte getPaypayFlag() {
        return paypayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.paypay_flag
     *
     * @param paypayFlag the value for user.paypay_flag
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setPaypayFlag(Byte paypayFlag) {
        this.paypayFlag = paypayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.paypay_account
     *
     * @return the value of user.paypay_account
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getPaypayAccount() {
        return paypayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.paypay_account
     *
     * @param paypayAccount the value for user.paypay_account
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setPaypayAccount(String paypayAccount) {
        this.paypayAccount = paypayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bank_flag
     *
     * @return the value of user.bank_flag
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public Byte getBankFlag() {
        return bankFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bank_flag
     *
     * @param bankFlag the value for user.bank_flag
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setBankFlag(Byte bankFlag) {
        this.bankFlag = bankFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bank_name
     *
     * @return the value of user.bank_name
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bank_name
     *
     * @param bankName the value for user.bank_name
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bank_branch
     *
     * @return the value of user.bank_branch
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bank_branch
     *
     * @param bankBranch the value for user.bank_branch
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bank_account
     *
     * @return the value of user.bank_account
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bank_account
     *
     * @param bankAccount the value for user.bank_account
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.profile_completed
     *
     * @return the value of user.profile_completed
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public Boolean getProfileCompleted() {
        return profileCompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.profile_completed
     *
     * @param profileCompleted the value for user.profile_completed
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setProfileCompleted(Boolean profileCompleted) {
        this.profileCompleted = profileCompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_at
     *
     * @return the value of user.created_at
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_at
     *
     * @param createdAt the value for user.created_at
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updated_at
     *
     * @return the value of user.updated_at
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updated_at
     *
     * @param updatedAt the value for user.updated_at
     *
     * @mbg.generated Wed Jan 28 17:17:06 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}